=== mice-software/maus/src/common_py/geometry/GDML_3_0_0/schema/GDML_MICE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
<!--++++++++++++++++++++++++++++++++++BASE TYPES+++++++++++++++++++++++++++++++++++++++++-->
    <xs:complexType name="G4MagnetType">
        <xs:attribute name="Name"/>
        <xs:attribute name="Type"/>
        <xs:attribute name="File_Location"/>        
    </xs:complexType>
    <xs:complexType name="TOFType">
        <xs:attribute name="TOF"/>
    </xs:complexType>
    <xs:complexType name="KLType">
        <xs:attribute name="KL"/>
    </xs:complexType>
    <xs:complexType name="CherenkovType">
        <xs:attribute name="Cherenkov"/>        
    </xs:complexType>
    <xs:complexType name="runMagnetType">
        <xs:attribute name="name" use="required" type="xs:NCName"/>
        <xs:attribute name="polarity" use="required" type="xs:NCName"/>
        <xs:attribute name="setCurrent" use="required" type="xs:decimal"/>
    </xs:complexType>
    <xs:complexType name="PositionType">
        <xs:attribute name="x" use="required" type="xs:double"/>
        <xs:attribute name="y" use="required" type="xs:double"/>
        <xs:attribute name="z" use="required" type="xs:double"/>
    </xs:complexType>
    <xs:complexType name="LengthType">
        <xs:attribute name="value" type="xs:double"/>
        <xs:attribute name="units" use="optional"/>
    </xs:complexType>
    <xs:complexType name="FileReferenceType">
        <xs:sequence>
            <xs:element name="Position" type="PositionType"/>
            <xs:element name="Rotation" type="PositionType"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:anyURI" use="required"></xs:attribute>
    </xs:complexType>
<!--++++++++++++++++++++++++++++++++Tracker Base TYPES+++++++++++++++++++++++++++++++++++++-->
    <xs:complexType name="NumberType">
        <xs:attribute name="Number" use="required" type="xs:integer"/>
    </xs:complexType>
    <xs:complexType name="CentralFibreType">
        <xs:attribute name="Number" use="required" fixed="112.5"/>
    </xs:complexType>
    <xs:complexType name="Delta_FType">
        <xs:attribute name="value" use="required" type="xs:double"/>
    </xs:complexType>
    <xs:complexType name="TrackerLengthType">
        <xs:attribute name="length" use="required" type="xs:double"/>
        <xs:attribute name="units" use="optional"/>
    </xs:complexType>
    <xs:complexType name="TrackerThicknessType">
        <xs:attribute name="thickness" use="required" type="xs:double"/>
        <xs:attribute name="units" use="optional"/>
    </xs:complexType>
    <xs:complexType name="TrackerMaterialType">
        <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="DetectorType">
        <xs:attribute name="type" use="required" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="PlaneType">
        <xs:attribute name="plane" use="required" type="xs:integer"/>
    </xs:complexType>
    <xs:complexType name="ActiveRadiusType">
        <xs:attribute name="R" use="required" type="xs:double"/>
        <xs:attribute name="unit" use="optional"/>
    </xs:complexType>
    <xs:complexType name="PitchType">
        <xs:attribute name="angle" use="required" type="xs:double"/>
        <xs:attribute name="unit" use="optional"/>
    </xs:complexType>
    <xs:complexType name="DiameterType">
        <xs:attribute name="dia" use="required" type="xs:double"/>
        <xs:attribute name="unit" use="optional"/>
    </xs:complexType>
    <xs:complexType name="InvisibleType">
        <xs:attribute name="True" use="required" type="xs:integer"/>
    </xs:complexType>
    <xs:complexType name="TrackerRotationType">
        <xs:attribute name="alpha" use="required" type="xs:double"/>
        <xs:attribute name="beta" use="required" type="xs:double"/>
        <xs:attribute name="gamma" use="required" type="xs:double"/>
        <xs:attribute name="units" use="optional"/>
    </xs:complexType>
    <xs:complexType name="ColourType">
        <xs:attribute name="red" use="required" type="xs:double"/>
        <xs:attribute name="green" use="required" type="xs:double"/>
        <xs:attribute name="blue" use="required" type="xs:double"/>
    </xs:complexType>
<!--++++++++++++++++++++++++++++++++Tracker Schema+++++++++++++++++++++++++++++++++++++-->
    <xs:complexType name="SciFi_Geo_Trkr_Type">
        <xs:annotation>
            <xs:documentation>
                This is the tracker type and describes the tracker as a whole.
                It is made up of geo_stn types.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Tracker" type="NumberType"/>
            <xs:element name="Position" type="PositionType"/>
            <xs:element name="Rotation" type="TrackerRotationType"/>
            <xs:element name="Length" type="LengthType"/>
            <xs:element name="Thickness" type="TrackerThicknessType"/>
            <xs:element name="Material" type="TrackerMaterialType"/>
            <xs:element name="Invisible" type="InvisibleType"/>
        </xs:sequence>
        <xs:attribute name="ID_Number" use="required" type="xs:integer"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="SciFi_Geo_Stn_Type">
        <xs:annotation>
            <xs:documentation>
                This is the Station type. It descirbes each station within
                this tracker. This component is made up of doublets.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Tracker" type="NumberType"/>
            <xs:element name="Position" type="PositionType"/>
            <xs:element name="Rotation" type="TrackerRotationType"/>
            <xs:element name="Length" type="LengthType"/>
            <xs:element name="Thickness" type="TrackerThicknessType"/>
            <xs:element name="Station" type="NumberType"/>
            <xs:element name="Material" type="TrackerMaterialType"/>
            <xs:element name="OpticsMaterialLength" type="LengthType"/>
        </xs:sequence>
        <xs:attribute name="ID_Number" use="required" type="xs:integer"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="SciFi_Geo_Double_Type">
        <xs:annotation>
            <xs:documentation>
                This is the id type. It holds all the default information about
                the tracker's doublets.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="View" type="NumberType"/>
            <xs:element name="CentralFibre" type="CentralFibreType"/>
            <xs:element name="Delta_F" type="Delta_FType"/>
            <xs:element name="Length" type="TrackerLengthType"/>
            <xs:element name="Thickness" type="TrackerThicknessType"/>
            <xs:element name="Material" type="TrackerMaterialType"/>
            <xs:element name="SensitiveDetector" type="DetectorType"/>
            <xs:element name="Plane" type="PlaneType"/>
            <xs:element name="ActiveRadius" type="ActiveRadiusType"/>
            <xs:element name="Pitch" type="PitchType"/>
            <xs:element name="FibreDiameter" type="DiameterType"/>
            <xs:element name="CoreDiameter" type="DiameterType"/>
            <xs:element name="Invisible" type="InvisibleType"/>
            <xs:element name="G4Detector" type="DetectorType"/>
            <xs:element name="MylarThickness" type="TrackerThicknessType"/>
        </xs:sequence>
        <xs:attribute name="ID_Number" use="required" type="xs:integer"/>
    </xs:complexType>
<!--+++++++++++++++++++++++++++++++++++MIDDLE TYPES++++++++++++++++++++++++++++++++++++++++-->
    <xs:complexType name="TrackerType">
        <xs:annotation>
            <xs:documentation>
                This is the Tacker Geometry Information
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Tracker" type="SciFi_Geo_Trkr_Type"/>
            <xs:element name="Station" type="SciFi_Geo_Stn_Type"/>
            <xs:element name="SciFiGeoDbl" type="SciFi_Geo_Double_Type" minOccurs="0"/>
        </xs:sequence>
        <!--<xs:sequence>
            <xs:element name="Component" maxOccurs="2">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Position" type="PositionType"/>
                        <xs:element name="Rotation" type="PositionType"/>
                        <xs:element name="Length" type="LengthType"/>
                        <xs:element name="Thickness" type="LengthType"/>
                        <xs:element name="Material" type="LengthType"/>
                        <xs:element name="Tracker" type="LengthType"/>
                        <xs:element name="Invisible" type="LengthType"/>
                        <xs:element name="Tracker_Element" type="FileReferenceType" maxOccurs="unbounded"></xs:element>
                    </xs:sequence>
                    <xs:attribute name="name"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>-->
    </xs:complexType>
    <xs:complexType name ="configurationType">
        <xs:sequence>
            <xs:element name="run">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="magnet" type="runMagnetType" minOccurs="0"/>                        
                    </xs:sequence>
                    <xs:attribute name="daqGateWidth" use="required" type="xs:decimal"/>
                    <xs:attribute name="daqTrigger" use="required" type="xs:integer"/>
                    <xs:attribute name="daqVersion" use="required" type="xs:decimal"/>
                    <xs:attribute name="endTime" use="required"/>
                    <xs:attribute name="isisBeamPositionX" use="required" type="xs:NCName"/>
                    <xs:attribute name="isisBeamPositionY" use="required" type="xs:NCName"/>
                    <xs:attribute name="isisNominalBeamCurrent" use="required" type="xs:decimal"/>
                    <xs:attribute name="isisNominalBeamLoss" use="required" type="xs:decimal"/>
                    <xs:attribute name="isisRepRate" use="required" type="xs:decimal"/>
                    <xs:attribute name="isisTargetFrequency" use="required" type="xs:integer"/>
                    <xs:attribute name="notes" use="required"/>
                    <xs:attribute name="optics" use="required" type="xs:NCName"/>
                    <xs:attribute name="protonAbsorberThickness" use="required" type="xs:NCName"/>
                    <xs:attribute name="pulseEnd" use="required" type="xs:integer"/>
                    <xs:attribute name="pulseStart" use="required" type="xs:integer"/>
                    <xs:attribute name="runNumber" use="required" type="xs:integer"/>
                    <xs:attribute name="runType" use="required" type="xs:NCName"/>
                    <xs:attribute name="startTime" use="required"/>
                    <xs:attribute name="status" use="required" type="xs:boolean"/>
                    <xs:attribute name="step" use="required" type="xs:decimal"/>
                    <xs:attribute name="targetDelay" use="required" type="xs:decimal"/>
                    <xs:attribute name="targetDepth" use="required" type="xs:decimal"/>
                    <xs:attribute name="targetDriveVoltage" use="required" type="xs:decimal"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="G4Field_InformationType">
        <xs:sequence>
            <xs:element name="G4Magnet_info" type="G4MagnetType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Detector_InformationType">
        <xs:sequence>
            <xs:element name="TOF" minOccurs="0" maxOccurs="3"/>
            <xs:element name="KL" minOccurs="0"/>
            <xs:element name="Cherenkov" minOccurs="0"/>
            <xs:element name="Tracker" type="TrackerType" minOccurs="0"/>
            <xs:element name="Tracker_Part" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
<!--++++++++++++++++++++++++++++++++++TOP TYPES+++++++++++++++++++++++++++++++++++++++++-->
    <xs:element name="MICE_Information">
        <xs:annotation>
            <xs:documentation>
                This Information is needed for the MICE experiment. It is
                translated through the CAD to Software translation system
                and is need for simulations. Some of this information comes
                direct from the control room and some is stored in MAUS 
                and combined with geometrical information from CADs.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Configuration_Information" type="configurationType" minOccurs="0">
                </xs:element>
                <xs:element name="G4Field_Information" type="G4Field_InformationType" minOccurs="0"/>
                <xs:element name="Detector_Information" type="Detector_InformationType" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>


<!-- <xs:element name="Station" substitutionGroup="Tracker_Part">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Position" type="PositionType"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:element> -->

=== mice-software/maus/src/common_py/geometry/gdmlSchema/GDML_3_0_0/schema/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<MICE_Information xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/matt/maus-littlefield/src/common_py/geometry/gdmlSchema/GDML_3_0_0/schema/GDML_MICE.xsd">
    <Configuration_Information>
        <run daqGateWidth="0" daqTrigger="0" daqVersion="0" endTime="endTime0" isisBeamPositionX="isisBeamPositionX0"
             isisBeamPositionY="isisBeamPositionY0" isisNominalBeamCurrent="0" isisNominalBeamLoss="0"
             isisRepRate="0" isisTargetFrequency="0" notes="notes0" optics="optics0" protonAbsorberThickness="protonAbsorberThickness0"
             pulseEnd="0" pulseStart="0" runNumber="0" runType="runType0" startTime="startTime0" status="false"
             step="0" targetDelay="0" targetDepth="0" targetDriveVoltage="0">
            <magnet name="name0" polarity="polarity0" setCurrent="0"/>
        </run>
    </Configuration_Information>
    <G4Field_Information>
        <G4Magnet_info Name="Name0" Type="Type0" File_Location="File_Location0"/>
        <G4Magnet_info Name="Name1" Type="Type1" File_Location="File_Location1"/>
    </G4Field_Information>
    <Detector_Information>
        <TOF>
        </TOF>
        <TOF>
        </TOF>
        <KL>
        </KL>
        <Cherenkov>
        </Cherenkov>
        <Tracker>
            <Component name="name1">
                <Position x="0" y="0" z="0"/>
                <Rotation x="0" y="0" z="0"/>
                <Length value="value0" units="units0"/>
                <Thickness value="value1" units="units1"/>
                <Material value="value2" units="units2"/>
                <Tracker value="value3" units="units3"/>
                <Invisible value="value4" units="units4"/>
                <Tracker_Element name="name2">
                    <Position x="0" y="0" z="0"/>
                    <Rotation x="0" y="0" z="0"/>
                </Tracker_Element>
                <Tracker_Element name="name3">
                    <Position x="0" y="0" z="0"/>
                    <Rotation x="0" y="0" z="0"/>
                </Tracker_Element>
            </Component>
            <Component name="name4">
                <Position x="0" y="0" z="0"/>
                <Rotation x="0" y="0" z="0"/>
                <Length value="value5" units="units5"/>
                <Thickness value="value6" units="units6"/>
                <Material value="value7" units="units7"/>
                <Tracker value="value8" units="units8"/>
                <Invisible value="value9" units="units9"/>
                <Tracker_Element name="name5">
                    <Position x="0" y="0" z="0"/>
                    <Rotation x="0" y="0" z="0"/>
                </Tracker_Element>
                <Tracker_Element name="name6">
                    <Position x="0" y="0" z="0"/>
                    <Rotation x="0" y="0" z="0"/>
                </Tracker_Element>
            </Component>
        </Tracker>
    </Detector_Information>
</MICE_Information>
